### ISSUE TITLE
masscan 'no target IP found' warning 

### ISSUE THREAD

**Issue by rsilvernagel** [carrier-io/dusty#97]
I'm getting the following warning from masscan when using either a url or IP address:

> dusty.scanners.dast.masscan.scanner - No target IP found. Exiting

My config is as follows:

    ```
    masscan: # masscan TCP port scanner
          target: http://portal-unstable.dev.f5aas.com  # scan target
          include_ports: 0-65535 # (optional) Ports to scan
          exclude_ports: 1,4-40,4444 # (optional) Ports to exclude
          save_intermediates_to: /data/intermediates/dast

```
 I've also tried replacing the url with an IP address but get the same message. I'd like to include this scanner in my dast tests but am not sure how to resolve this without more documentation.

**Comment by arozumenko** [comment]
Hi @rsilvernagel,
may I suggest you to try:
`
masscan: # masscan TCP port scanner
      target: IP  # scan target instead of http://mysite.com:80
      include_ports: 0-65535 # (optional) Ports to scan
      exclude_ports: 1,4-40,4444 # (optional) Ports to exclude
      save_intermediates_to: /data/intermediates/dast
`

**Comment by arozumenko** [comment]
Here is the config I've used to verify, seems like working fine
```
config_version: 2
global:  # Common settings for all suites
  settings:  # Settings
    project_name: DemoMasscan  # Project name
  processing: # Processing config
    min_severity_filter: # Filters findings below minimal severity level
      severity: Info # Minimal severity level to report, one of: Critical, High, Medium, Low, Info
  reporters: # Reporters config
    html: # HTML reporter
      file: /tmp/reports/report.html
    junit:
      file: /tmp/reports/report.xml
suites: # Test suites
  dast_masscan:
    settings: # General config
      project_description: Loopback
      environment_name: prod # Environment under testing (branch/module for DAST)
      testing_type: DAST # DAST or SAST
      scan_type: full # full, incremental or other scan description (e.g.: qualys, authorized, etc)
      build_id: '1' # Build number (or some other identifier)
    scanners:
      dast:
        masscan: # masscan TCP port scanner
          target: 192.168.1.143  # scan target instead of http://mysite.com:80
          include_ports: 0-65535 # (optional) Ports to scan
          exclude_ports: 1,4-40,4444 # (optional) Ports to exclude
          save_intermediates_to: /data/intermediates/dast
```

execution command
```
docker run -t -v /tmp/dast/dast.yaml:/tmp/dast.yaml -v /tmp/dast/reports:/tmp/reports  getcarrier/dast:latest run -c /tmp/dast.yaml -s dast_masscan -d
```
generated set of info level findings, although there can be an issue if all ports on target IP is closed, then we will get an exception @LifeDJIK to handle.

@rsilvernagel we may jump on the call and describe you how we configure and use dast and sast in pipelines
